// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200215131642_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Domain.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00b9e2b3-2486-4e37-a51a-21df39ca03a9"),
                            FullUrl = "http://www.google.com",
                            IsPublic = true,
                            ShortUrl = "/1"
                        },
                        new
                        {
                            Id = new Guid("f569cde1-4c52-4c48-8860-5119a51d2e2c"),
                            FullUrl = "http://www.facebook.com",
                            IsPublic = true,
                            ShortUrl = "/2"
                        },
                        new
                        {
                            Id = new Guid("870d738a-1a4c-4e7c-ab83-091b9428d186"),
                            FullUrl = "http://www.microsoft.com",
                            IsPublic = false,
                            ShortUrl = "/3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
